#import "./EmailsForm_User.graphql"

query SettingsEmails {
  currentUser {
    id
    isVerified
    userEmails(first: 50) {
      nodes @list(name: "User_Emails") {
        id
        ...EmailsForm_UserEmail
      }
    }
  }
}
