name: Windows Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      CI: true
      CONFIRM_DROP: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Set up PostgresSQL 14
        uses: ikalnytskyi/action-setup-postgres@v3

      # These all need to be separate steps on Windows because a failure of a
      # command doesn't fail the whole job step - see
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

      - name: yarn
        run: |
          cp .env.ci .env
          yarn --frozen-lockfile
      - name: setup
        run: yarn setup
      - name: build
        run: yarn build
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test --ci
      - name: depcheck
        run: yarn depcheck
